# Site settings
title: Air
email: matt_thomas@fastmail.fm
description: "An ultra-minimalist Jekyll theme inspired by Information Architects."
baseurl: "/air"
url: "http://mattthomas.info"

# Build settings
markdown: kramdown
permalink: :title
